import React, {useMemo, useState} from "react";
import {
  Coins, TrendingUp, TrendingDown, WalletCards, BriefcaseBusiness, Users, Trophy,
  Handshake, Landmark, BarChart3, Receipt, ArrowUpRight, ArrowDownRight,
  ChevronRight, ChevronDown, FileText, ShieldCheck, CircleDollarSign, Building2,
  Banknote, Percent, CalendarDays, Search, X
} from "lucide-react";
import "./finance.css";

const revenue = [
  ["Broadcasting Rights",42.3,"£33,160,000"],["Matchday Revenue",18.7,"£14,660,000"],
  ["Sponsorships",16.8,"£13,190,000"],["Merchandise",9.2,"£7,210,000"],
  ["Competitions",7.6,"£5,960,000"],["Other Income",5.4,"£4,230,000"]
];
const spending = [
  ["Player Wages",48.8,"£42,300,000"],["Staff Wages",9.1,"£7,860,000"],
  ["Transfers",21.6,"£18,750,000"],["Facilities & Stadium",7.4,"£6,420,000"],
  ["Operating Costs",6.5,"£5,610,000"],["Other Expenses",6.7,"£5,800,000"]
];
const contracts = [
  ["Bruno Fernandes","CM","30","Expiring Soon","30 Jun 2026","£350,000/w"],
  ["Casemiro","DM","33","Expiring Soon","30 Jun 2026","£300,000/w"],
  ["Rasmus Højlund","ST","22","Renewal In Progress","30 Jun 2028","£250,000/w"],
  ["Luke Shaw","LB","29","Contract Ok","30 Jun 2027","£200,000/w"],
  ["Alejandro Garnacho","RW","21","Contract Ok","30 Jun 2028","£240,000/w"]
];
const transactions = [
  ["14 Dec 2025","Matchday vs Aston Villa","Matchday Revenue","+£3,200,000","Completed"],
  ["12 Dec 2025","Adidas Sponsorship Payment","Sponsorships","+£1,200,000","Completed"],
  ["10 Dec 2025","TV Rights Payment","Broadcasting","+£4,800,000","Completed"],
  ["08 Dec 2025","Player Wages (December)","Player Wages","-£2,480,000","Completed"],
  ["06 Dec 2025","Facility Upgrade","Facilities","-£2,100,000","Completed"]
];

function FinanceTabs({tab,setTab}){
  return <div className="finance-tabs">{[
    ["overview","Overview"],["revenue","Revenue"],["spending","Spending & Budgets"],["contracts","Contracts & Club Finance"]
  ].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
}
function Ring({value,label="",className=""}){return <div className={`finance-ring ${className}`} style={{"--p":`${value*3.6}deg`}}><div><b>{value}%</b>{label&&<span>{label}</span>}</div></div>}
function Bar({value,max=100}){return <div className="finance-bar"><i style={{width:`${Math.min(100,value/max*100)}%`}}/></div>}
function Money({children,down=false}){return <strong className={down?"money down":"money"}>{children}</strong>}
function Panel({title,icon:Icon,action,children,className=""}){return <section className={`finance-panel ${className}`}><div className="finance-panel-title"><h2>{Icon&&<Icon/>}{title}</h2>{action&&<button>{action}<ChevronRight/></button>}</div>{children}</section>}
function MiniChart({forecast=false}){const vals=forecast?[42,48,57,62,70,76]:[62,72,58,89,112,142,168]; return <div className="mini-chart"><div className="chart-y"><span>£200M</span><span>£150M</span><span>£100M</span><span>£50M</span><span>£0</span></div><div className="chart-area">{vals.map((v,i)=><div className="chart-col" key={i}><i style={{height:`${Math.max(8,v/2)}%`}}/><span>{forecast?["Jan 26","Feb 26","Mar 26","Apr 26","May 26","Jun 26"][i]:["Jul 25","Aug 25","Sep 25","Oct 25","Nov 25","Dec 25"][i]}</span></div>)}</div></div>}
function RevenueBreakdown(){return <Panel title="Revenue Breakdown" icon={BarChart3}><div className="donut-layout"><div className="donut revenue-donut"><span>£78.4M<small>Total</small></span></div><div className="legend-list">{revenue.map(([n,p,v])=><div key={n}><i/ ><span>{n}</span><b>{p}%</b><strong>{v}</strong></div>)}</div></div></Panel>}
function SpendingBreakdown(){return <Panel title="Expenses Breakdown" icon={Receipt}><div className="donut-layout"><div className="donut expense-donut"><span>£56.2M<small>Total</small></span></div><div className="legend-list">{[["Player Wages",52.4,"£29,480,000"],["Staff Wages",12.6,"£7,090,000"],["Transfers",14.3,"£8,040,000"],["Facilities",8.1,"£4,560,000"],["Operating Costs",7.8,"£4,390,000"],["Other Expenses",4.8,"£2,650,000"]].map(([n,p,v])=><div key={n}><i/><span>{n}</span><b>{p}%</b><strong>{v}</strong></div>)}</div></div></Panel>}
function Overview(){return <div className="finance-content">
  <div className="finance-grid overview-top">
    <Panel title="Club Finances Overview" icon={Coins}><div className="balance-row"><div className="big-balance"><WalletCards/><span>Current Balance</span><Money>£142,560,000</Money><small>Last Month <em>▲ +£12,400,000</em></small></div><div className="finance-summary"><div><span>Total Income</span><Money>£78,420,000</Money></div><div><span>Total Expenses</span><Money down>£56,210,000</Money></div><div><span>Net Profit/Loss</span><Money>+£22,210,000</Money></div></div></div><div className="trend-title"><span>Balance Trend <small>(Last 6 Months)</small></span></div><MiniChart/></Panel>
    <RevenueBreakdown/><SpendingBreakdown/>
  </div>
  <div className="finance-grid overview-middle">
    <Panel title="Transfer Budget" icon={WalletCards}><div className="budget-number"><span>Available Transfer Funds</span><Money>£120,000,000</Money></div><Bar value={60}/><div className="two-stat"><span>Spent this season <b>£48,750,000</b></span><span>Remaining <b>£71,250,000</b></span></div><button className="purple-action">View Transfer Budget <ChevronRight/></button></Panel>
    <Panel title="Wage Structure" icon={Banknote} action="View Wage Structure"><div className="wage-head"><Ring value={58}/><div><span>Total Wage Bill</span><Money>£29,480,000</Money><small>▲ +14% vs last season</small></div></div><div className="wage-lines"><span>First Team <b>£22,400,000</b></span><span>U21 Wages <b>£3,120,000</b></span><span>Staff Wages <b>£7,090,000</b></span><span>Wage Room <b>£35,510,000</b></span></div></Panel>
    <Panel title="Key Contracts" icon={FileText} action="View All"><div className="contract-mini">{contracts.slice(0,5).map(c=><div key={c[0]}><b>{c[0]}</b><span>{c[3]}</span><small>{c[4]}</small><strong>{c[5]}</strong></div>)}</div></Panel>
  </div>
  <div className="finance-grid overview-bottom"><Panel title="Sponsors" icon={Handshake} action="View Sponsors"><div className="sponsor-summary"><div><span>Total Sponsorship Income</span><Money>£13,190,000</Money><small>▲ +20% vs last season</small></div><div><span>Active Deals</span><b>4</b><small>1 year 6 months average</small></div></div><div className="sponsor-list">{[["Adidas","£6,500,000"],["TeamViewer","£3,200,000"],["DHL","£2,100,000"],["Snapdragon","£1,390,000"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>30 Jun 2027</small></div>)}</div></Panel>
    <Panel title="Board & Club Funds" icon={Landmark} action="View Board Details"><div className="fund-list"><div>Board Investment <Money>£50,000,000</Money><span className="status good">Available</span></div><div>Club Loan <b>£0</b><span className="status">Not needed</span></div><div>Financial Restrictions <b>None</b></div></div></Panel>
    <Panel title="Financial Forecast" icon={BarChart3} action="View Full Forecast"><MiniChart forecast/></Panel>
  </div>
  <Transactions/>
 </div>}
function Transactions(){return <Panel title="Recent Financial Transactions" icon={Receipt} action="View All"><div className="transaction-table"><div className="t-head"><span>DATE</span><span>DESCRIPTION</span><span>CATEGORY</span><span>AMOUNT</span><span>STATUS</span></div>{transactions.map(t=><div key={t[0]+t[1]}><span>{t[0]}</span><span>{t[1]}</span><span>{t[2]}</span><Money down={t[3].startsWith("-")}>{t[3]}</Money><b className="status good">{t[4]}</b></div>)}</div></Panel>}
function Revenue(){return <div className="finance-content"><div className="finance-grid revenue-top"><Panel title="Revenue Overview" icon={TrendingUp}><div className="revenue-hero"><div><span>Total Revenue (Season to Date)</span><Money>£78,420,000</Money><small>▲ +18% vs last season</small></div><div className="last-season"><span>Last Season</span><b>£66,560,000</b></div><Ring value={82}/></div><MiniChart/></Panel><RevenueBreakdown/><Panel title="Revenue Summary" icon={CircleDollarSign}><div className="summary-list"><div>Total Revenue <Money>£78,420,000</Money></div><div>Last Season <b>£66,560,000</b></div><div>Monthly Average <b>£13,070,000</b></div><div>Highest Month <b>Oct 2025 · £16,800,000</b></div><div>Lowest Month <b>Jul 2025 · £9,420,000</b></div></div><div className="green-callout">Revenue is up by 18%<small>Compared to the same period last season.</small></div></Panel></div>
<div className="revenue-cards">{[["Matchday Revenue","£14,660,000","18.7% of total","Stadium ticketing"],["Broadcasting Revenue","£33,160,000","42.3% of total","Domestic TV rights"],["Sponsorships","£13,190,000","16.8% of total","Kit sponsorship"],["Merchandise","£7,210,000","9.2% of total","Shirt sales"],["Competitions","£5,960,000","7.6% of total","Domestic cups"],["Other Income","£4,230,000","5.4% of total","Advertising"]].map(([n,v,p,s])=><section className="finance-panel revenue-card" key={n}><h3>{n}</h3><Money>{v}</Money><span>{p}</span><div className="fake-photo">{s}</div><p>Key source</p><b>{s}</b><button className="purple-action">View Details <ChevronRight/></button></section>)}</div>
<div className="finance-grid revenue-bottom"><Panel title="Top Revenue Sources" icon={BarChart3}>{revenue.map(([n,p,v],i)=><div className="rank-line" key={n}><b>{i+1}</b><span>{n}</span><Bar value={p} max={45}/><strong>{v}</strong></div>)}</Panel><Panel title="Revenue Goals & Targets" icon={Trophy}>{revenue.slice(0,5).map(([n,p,v])=><div className="goal-line" key={n}><span>{n}</span><b>{v}</b><em>{Math.round(p+50)}%</em><Bar value={p+50}/></div>)}</Panel><Transactions/></div>
</div>}
function Spending(){return <div className="finance-content"><div className="finance-grid spending-top"><Panel title="Club Spending Overview" icon={Coins}><div className="donut-layout spending-main"><div className="donut spending-donut"><span>£86.74M<small>Total Spending</small></span></div><div className="legend-list">{spending.map(([n,p,v])=><div key={n}><i/><span>{n}</span><b>{v}</b><strong>{p}%</strong></div>)}</div></div></Panel><Panel title="Key Budget Summary" icon={WalletCards}><div className="budget-summary-list"><div>Transfer Budget <Money>£200,000,000</Money><span>Available</span></div><div>Wage Budget <Money>£120,000,000</Money><span>Available</span></div><div>Remaining Wage Room <Money>£25,650,000</Money></div><div>Total Spending (Season) <Money>£86,740,000</Money></div><div>Budget Utilisation <Bar value={43}/></div></div></Panel><Panel title="Wage Structure" icon={Banknote} action="View Details"><div className="wage-head"><Ring value={58}/><div><span>Total Wage Bill</span><Money>£42,300,000</Money><small>▲ +12% vs last season</small></div></div>{[["First Team","£28,400,000",67.1],["U21 / Youth","£4,230,000",10],["Staff Wages","£7,860,000",18.6],["Other","£810,000",1.9]].map(x=><div className="distribution" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}%</em><Bar value={x[2]}/></div>)}</Panel></div>
<div className="finance-grid spending-middle"><Panel title="Detailed Spending Breakdown" icon={Receipt}><div className="spending-table head"><span>CATEGORY</span><span>THIS MONTH</span><span>SEASON TOTAL</span><span>% OF TOTAL</span></div>{spending.map(([n,p,v])=><div className="spending-row" key={n}><b>{n}</b><span>£{n==="Player Wages"?"3,420,000":n==="Staff Wages"?"690,000":n==="Transfers"?"2,180,000":n==="Facilities & Stadium"?"520,000":n==="Operating Costs"?"480,000":"390,000"}</span><span>{v}</span><span>{p}%</span></div>)}<div className="total-row"><b>Total Spending</b><strong>£7,680,000</strong><strong>£86,740,000</strong><strong>100%</strong></div></Panel><Panel title="Transfer Budget" icon={ArrowUpRight} action="View Details"><Money>£200,000,000</Money><span>Available Transfer Funds</span><Bar value={100}/><div className="two-stat"><span>Spent this season <b>£48,750,000</b></span><span>Remaining <b>£151,250,000</b></span></div><h3>Budget Allocation</h3>{[["First Team",70,"£140,000,000"],["U21 / Youth",15,"£30,000,000"],["Other",15,"£30,000,000"]].map(x=><div className="distribution" key={x[0]}><span>{x[0]}</span><em>{x[1]}%</em><Bar value={x[1]}/><b>{x[2]}</b></div>)}</Panel><Panel title="Player & Staff Wages" icon={Users} action="View All"><div className="earner-cols"><div><h3>Top Earners (Players)</h3>{[["Bruno Fernandes","£350,000"],["Casemiro","£300,000"],["Rasmus Højlund","£250,000"],["Marcus Rashford","£240,000"],["Matthijs de Ligt","£220,000"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div><h3>Top Earners (Staff)</h3>{[["Erik ten Hag","£200,000"],["R. van Nistelrooy","£150,000"],["Steve McClaren","£120,000"],["Jason Wilcox","£100,000"],["Benni McCarthy","£90,000"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></Panel></div>
<div className="finance-grid spending-bottom"><Panel title="Transfer Spending History" icon={ArrowUpRight} action="View All">{[["12 Dec 2025","M. Rashford","Man Utd → Al Hilal","£40,000,000"],["05 Dec 2025","L. Martínez","Ajax → Man Utd","£36,000,000"],["28 Nov 2025","A. Garnacho","Man Utd → Napoli","£28,000,000"],["15 Nov 2025","K. Mainoo","Man Utd → Bayern","£22,000,000"],["03 Nov 2025","S. Amrabat","Fiorentina → Man Utd","£18,000,000"]].map(x=><div className="history-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><span>{x[2]}</span><strong>{x[3]}</strong></div>)}</Panel><Panel title="Operating Costs" icon={Building2} action="View Details">{[["Training Facilities","£1,200,000"],["Youth Academy","£980,000"],["Travel & Accommodation","£860,000"],["Medical & Physio","£740,000"],["Miscellaneous","£1,830,000"]].map(x=><div className="cost-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<div className="cost-total">Total Operating Costs <b>£5,610,000</b></div></Panel><Panel title="Budget Forecast" icon={BarChart3} action="View Details"><MiniChart forecast/></Panel></div></div>}
function Contracts(){const [selected,setSelected]=useState(contracts[0]);return <div className="finance-content"><div className="finance-grid contracts-top"><Panel title="Contracts Overview" icon={FileText} action="View All Contracts"><div className="contract-metrics"><div><b>32</b><span>Active Contracts</span><small>+1 this month</small></div><div><b>6</b><span>Expiring (≤ 6 months)</span><small>-2 this month</small></div><div><b>3</b><span>Renewals in Progress</span><small>+1 this month</small></div><div><b>£176.4M</b><span>Total Wage Commitment</span><small>per year</small></div></div><div className="contract-table"><div className="t-head"><span>PLAYER</span><span>POSITION</span><span>AGE</span><span>STATUS</span><span>CONTRACT EXPIRES</span><span>ACTION</span></div>{contracts.map(c=><button className="contract-row" key={c[0]} onClick={()=>setSelected(c)}><b>{c[0]}</b><span>{c[1]}</span><span>{c[2]}</span><span className={`status ${c[3].includes("Expiring")?"warn":c[3].includes("Renewal")?"blue":"good"}`}>{c[3]}</span><span>{c[4]}</span><strong>{c[3].includes("Contract Ok")?"—":"Renew"}</strong></button>)}</div></Panel><Panel title="Player Contract Details" icon={FileText}><div className="selected-contract"><div className="portrait">{selected[0].split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><h3>{selected[0]}</h3><span>{selected[1]} · Portugal</span><b>Age {selected[2]}</b><div className="stars">★★★★★ <small>8/10</small></div></div></div><div className="contract-details">{[["Contract Type","Full Time"],["Contract Length","3 Years"],["Weekly Wage",selected[5]],["Annual Wage","£18,200,000"],["Signing Bonus","£10,000,000"],["Agent Fee","£5,000,000"],["Release Clause","£120,000,000"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><button className="purple-action">Negotiate Contract <Handshake/></button></Panel><Panel title="Club Finances & Partners" icon={Handshake} action="View Details"><h3>Sponsors</h3><Money>£42,300,000</Money><span>5 Active Deals · / season</span>{[["TeamViewer","£12,000,000"],["Adidas","£10,500,000"],["DXC Technology","£8,500,000"],["Chevrolet","£6,200,000"],["Tezos","£4,100,000"]].map(x=><div className="partner-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<hr/><div className="fund-list"><div>Available Funds <Money>£50,000,000</Money></div><div>Board Investment <b>£25,000,000</b></div><div>Loans <b>£0</b></div><div>Financial Restrictions <span className="status good">None</span></div></div><div className="financial-health"><Ring value={82}/><span>Financial Health</span><b>Stable</b></div></Panel></div>
<div className="finance-grid contracts-bottom"><Panel title="Staff Contracts" icon={Users} action="View All Staff">{[["Erik ten Hag","Manager","30 Jun 2027","Ok"],["Ruben Amorim","Assistant Manager","30 Jun 2026","Renewal"],["Benni McCarthy","First Team Coach","30 Jun 2026","Ok"],["John Murtough","Director of Football","30 Jun 2026","Ok"],["Jason Wilcox","Technical Director","30 Jun 2027","Ok"]].map(x=><div className="staff-contract" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><span>{x[2]}</span><strong className={x[3]==="Renewal"?"warn":"good"}>{x[3]}</strong></div>)}</Panel><Panel title="Contract Commitments" icon={Coins} action="View All"><div className="commit-list">{[["Total First Team Contracts","£142,000,000"],["Total Staff Contracts","£34,600,000"],["Total Bonuses (committed)","£18,700,000"],["Total Agent Fees (committed)","£9,800,000"],["Total Contract Commitments","£205,100,000"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></Panel><Panel title="Key Financial Metrics" icon={Percent}><div className="metric-stack"><div>Wage to Turnover Ratio <b>58%</b></div><div>Transfer Spend (Season) <b>£48,750,000</b></div><div>Net Spend / Income <b>£22,400,000</b></div><div>Operating Costs <b>£6,100,000</b></div><div>Profit / Loss (Season) <Money>+£22,100,000</Money></div></div></Panel><Panel title="Financial Forecast" icon={BarChart3} action="View Forecast"><MiniChart forecast/></Panel></div><Transactions/></div>}

export default function FinanceScreen(){const [tab,setTab]=useState("overview"); return <div className="finance-page"><FinanceTabs tab={tab} setTab={setTab}/>{tab==="overview"?<Overview/>:tab==="revenue"?<Revenue/>:tab==="spending"?<Spending/>:<Contracts/>}</div>}
